appmailsend/urls.py
from django.urls import path

from appmailsend.apps import AppmailsendConfig

from appmailsend.views import index, mailingsettingsListView, ClientCreateView, ClientUpdateView, \
    ClientDetailView, mailingsettingsCreateView, mailingsettingsUpdateView, mailingsettingsDetailView, ClientListView, \
    ClientDeleteVeiw, mailingsettingsDeleteVeiw, mailinglogListView, mailinglogDeleteVeiw, mailinglogDetailView, \
    new_app_send_mail_schedule

app_name = AppmailsendConfig.name
urlpatterns = [
    path('', index, name='index'),

    path('client/', ClientListView.as_view(), name='client'),
    path('client/create/', ClientCreateView.as_view(), name='Client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='Client_update'),
    path('info/<int:pk>/', ClientDetailView.as_view(), name='detail_Client'),
    path('delete/<int:pk>', ClientDeleteVeiw.as_view(), name='Client_delete'),

    path('mailingsettings/', mailingsettingsListView.as_view(), name='mailingsettings'),
    path('mailingsettings/create/', mailingsettingsCreateView.as_view(), name='mailingsettings_create'),
    path('mailingsettings/<int:pk>/update/', mailingsettingsUpdateView.as_view(), name='mailingsettings_update'),
    path('mailingsettings_info/<int:pk>/', mailingsettingsDetailView.as_view(), name='mailingsettings_detail'),
    path('mailingsettings_delete/<int:pk>', mailingsettingsDeleteVeiw.as_view(), name='mailingsettings_delete'),
    # path('mailingsettings/send_test/', send_test_mail, name='mailingsettings_send_test_mail'),

    path('mailinglog/', mailinglogListView.as_view(), name='mailinglog'),
    path('mailinglog_info/<int:pk>/', mailinglogDetailView.as_view(), name='mailinglog_detail'),
    path('mailinglog_delete/<int:pk>', mailinglogDeleteVeiw.as_view(), name='mailinglog_delete'),

    path('mailinglog/test_send_mail_schedule/', new_app_send_mail_schedule, name='new_app_send_mail_schedule'),
]
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListVeiw, BlogDetailVeiw, BlogUpdateView, BlogDeleteVeiw

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListVeiw.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailVeiw.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteVeiw.as_view(), name='delete'),
]
  # + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appmailsend.urls', namespace='appmailsend')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls',namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, check_email
)

app_name = UsersConfig.name
# login/
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('check_email/<str:key>', check_email, name='check_email'),
    # path('chm_send/<str:key>>', chm_send, name='chm_send'),
]

appmailsend/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Q

from config import settings


class Client(models.Model):
    """ Клиенты получатели рассылок от пользователей"""
    name = models.CharField(max_length=100, verbose_name='Клиент')
    description = models.CharField(max_length=250, verbose_name='Описание клиента', null=True, blank=True)
    email = models.EmailField(unique=True, verbose_name='e-mail ')

    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания', null=True, blank=True)
    last_modified_date = models.DateTimeField(auto_now_add=True, verbose_name='дата последнего изменения', null=True,
                                              blank=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Создатель')

    def __str__(self):
        return f'{self.name} '

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('name',)

class mailingsettings(models.Model):
    """ Настройка рассылки"""
    mailing_time = models.TimeField(verbose_name='время рассылки')
    start_of_mailing = models.DateTimeField(verbose_name='Дата начала рассылки')
    day = "day"
    week = "week"
    month = "month"
    Mailing_schedule_ch=[
        (day, "Ежедневно"),
        (week, "Еженедельно"),
        (month, "Ежемесячно"),
    ]
    Mailing_schedule = models.CharField(max_length=5, choices=Mailing_schedule_ch, default=day, verbose_name='График рассылки')

    completed = "completed"
    created = "created"
    launched = "launched"
    status_ch = [
        (completed, "завершена"),
        (created, "создана"),
        (launched, "запущена"),
    ]

    status = models.CharField(max_length=10, choices=status_ch, default=day,
                                    verbose_name='Статус рассылки')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Создатель')
    # client = models.ManyToManyField(Client, Q(owner_id= Client.owner))
    # client = models.ManyToManyField(Client,  limit_choices_to={'owner': models.F('owner')}, null=True,blank=True, verbose_name='Получатели')
    client = models.ManyToManyField(Client, )

    subject_email = models.CharField(max_length=250, null=True, blank=True, verbose_name="Тема письма")
    body_email = models.TextField(null=True, blank=True, verbose_name="Тело письма")

    def __str__(self):
        return f'Рассылка начиная с {self.start_of_mailing} - {self.Mailing_schedule} в {self.mailing_time}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('start_of_mailing',)

class MailingMessage(models.Model):
    """Сообщение для рассылки не удобно, не логично перенес в настройку рассылки"""
    subject_email = models.CharField(max_length=250, verbose_name="Тема письма")
    body_email = models.TextField(verbose_name="Тело письма")
    settings = models.OneToOneField(to='mailingsettings', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Создатель')

    def __str__(self):
        return f'{self.subject_email}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения для рассылки '
        ordering = ('subject_email',)


class MailingLog(models.Model):
    """ лог рассылки """
    time_mailing = models.DateTimeField(verbose_name='Дата рассылки')
    succes_mail = models.BooleanField(default=False, verbose_name='Успешная отправка')
    answer = models.TextField(null=True, blank=True, verbose_name="Ответ сервера")


    client = models.ForeignKey('Client', on_delete=models.SET_NULL, null=True, blank=True,  verbose_name='Получатель')
    owner = models.ForeignKey('mailingsettings', on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Создатель')

    def __str__(self):
        return f'{self.time_mailing} - {self.answer} '

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ('time_mailing',)

appmailsend/forms.py
from django import forms
from django.forms import TimeInput, DateInput

from appmailsend.models import Client, mailingsettings, MailingMessage, MailingLog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Client
        exclude = 'owner',
        fields = '__all__'


class mailingsettingsForm(StyleFormMixin, forms.ModelForm):
    def __init__(self,   *args, **kwargs):
        self.user = kwargs.pop('user',None)
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'start_of_mailing':
                field.widget = DateInput(attrs={'type': 'date-local'})
            elif field_name == 'mailing_time':
                field.widget = TimeInput(attrs={'type': 'time'})



        self.fields['client'].queryset = Client.objects.filter(owner=self.user)
        # widgets = {'mailing_time': TimeInput()}

    class Meta:
        model = mailingsettings
        exclude = ('owner',)
        fields = '__all__'

appmailsend/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from appmailsend.forms import ClientForm, mailingsettingsForm
from appmailsend.models import Client, MailingLog, mailingsettings
from appmailsend.services import app_send_mail, app_send_mail_schedule


def index(request):

    if request.user.is_authenticated:
        context = {

            'object_count': Client.objects.filter(owner=request.user).count(),
            # 'Log_count': MailingLog.objects.filter(owner=request.user).count(),
            # 'succes_mail_count': MailingLog.objects.filter(owner=request.user, succes_mail=True).count(),
            'mailingsettings_count': mailingsettings.objects.filter(owner=request.user).count(),
            'title': f'Рассылка пользователя - {request.user}'
        }
    else:
        context = {

            'object_count': 0,
            # 'Log_count': 0,
            # 'succes_mail_count': 0,
            'mailingsettings_count': 0,
            'title': f'Авторизуйтесь для работы с сервисом'
        }
    return render(request, 'appmailsend/index.html', context)



class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': 'клиенты'
    }
    template_name = 'client_list.html'

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='Менеджер') or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(owner=user.pk)
        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    extra_context = {
        'title': 'Добавление клиента'
    }
    form_class = ClientForm
    success_url = reverse_lazy('appmailsend:client')
    login_url = 'users:login'

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    extra_context = {
        'title': 'Редактирование клиента'
    }
    form_class = ClientForm
    success_url = reverse_lazy('appmailsend:client')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.object.owner == self.request.user and not self.request.is_superuser:
            raise PermissionDenied
        return self.object

    # def get_context_data(self, *args, **kwargs):
    #     context_data = super().get_context_data(*args, **kwargs)
    #     VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
    #     if self.request.method == 'POST':
    #         context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
    #     else:
    #         context_data['formset'] = VersionFormset(instance=self.object)
    #
    #     # context_data['formset'] = formset
    #     return context_data
    #
    # def form_valid(self, form):
    #     # context_data =
    #     formset = self.get_context_data()['formset']
    #     self.object = form.save()
    #
    #     if formset.is_valid():
    #         formset.instance = self.object
    #         formset.save()
    #
    #     return super().form_valid(form)


class ClientDetailView(DetailView):
    model = Client
    extra_context = {
        'title': 'Информация по клиенту '
    }
    form_class = ClientForm
    success_url = reverse_lazy('appmailsend:client')

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #
    #     context_data['version_set'] = get_version_list(self.object.pk)
    #     return context_data

class ClientDeleteVeiw(DeleteView):
    model = Client
    extra_context = {
        'title': 'Delete Client'
    }
    success_url = reverse_lazy('appmailsend:client')

class mailingsettingsListView(LoginRequiredMixin, ListView):
    model = mailingsettings
    extra_context = {
        'title': 'Настройки рассылок'
    }
    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='Менеджер') or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(owner=user.pk)
        return queryset

class mailingsettingsCreateView(LoginRequiredMixin, CreateView):
    model = mailingsettings
    extra_context = {
        'title': 'Добавление рассылки'
    }
    form_class = mailingsettingsForm
    success_url = reverse_lazy('appmailsend:mailingsettings')
    login_url = 'users:login'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class mailingsettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = mailingsettings
    extra_context = {
        'title': 'Редактирование рассылки'
    }
    form_class = mailingsettingsForm
    success_url = reverse_lazy('appmailsend:mailingsettings')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.object.owner == self.request.user and not self.request.is_superuser:
            raise PermissionDenied
        return self.object

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class mailingsettingsDetailView(DetailView):
    model = mailingsettings
    extra_context = {
        'title': 'Информация по рассылке '
    }
    form_class = mailingsettingsForm
    success_url = reverse_lazy('appmailsend:mailingsettings')


    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #
    #
    # return context_data

class mailingsettingsDeleteVeiw(DeleteView):
    model = mailingsettings
    extra_context = {
        'title': 'Delete settings mailing'
    }
    success_url = reverse_lazy('appmailsend:mailingsettings')


class mailinglogListView(LoginRequiredMixin, ListView):
    model = MailingLog
    extra_context = {
        'title': 'Логи рассылок'
    }
    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='Менеджер') or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(owner=user.pk)
        return queryset


class mailinglogDetailView(DetailView):
    model = MailingLog
    extra_context = {
        'title': 'Детали рассылки'
    }
    form_class = mailingsettingsForm
    success_url = reverse_lazy('appmailsend:mailinglog')




class mailinglogDeleteVeiw(DeleteView):
    model = MailingLog
    extra_context = {
        'title': 'Delete MailingLog'
    }
    success_url = reverse_lazy('appmailsend:mailinglog')



def new_app_send_mail_schedule(request):
    app_send_mail_schedule()
    return redirect(reverse_lazy('appmailsend:mailinglog'))

appmailsend/templates/appmailsend/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{title}}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css'%}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Рассылки</h4>
                    <p class="text-muted">
                        Рассылка писем</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'appmailsend:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'appmailsend:client' %}" class="text-white">Клиенты</a></li>
                        <li><a href="{% url 'appmailsend:mailingsettings' %}" class="text-white">Рассылки</a></li>
                        <li><a href="{% url 'appmailsend:mailinglog' %}" class="text-white">Логи рассылки</a></li>

                        <li><a href="{% url 'blog:list' %}" class="text-white">Блог</a></li>
                        <li><a href="{% url 'appmailsend:new_app_send_mail_schedule' %}" class="text-white">test</a>

                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:generate_new_password' %}" class="text-white">Сбросить пароль</a>
                        </li>
                        <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                        <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                        <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Клиенты</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{title}}</h1>

        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}


        </div>
    </div>

</main>


<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

appmailsend/templates/appmailsend/client_confirm_delete.html
{% extends 'appmailsend/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">

            <div class="col-10">
                <div class="cart">
                    <div class="cart-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить запись "{{ object.title }}"</p>
                            <button type="submit" class="btn btn-danger">
                                Продолжить
                            </button>
                            <a href="{% url 'blog:list' %}"  type="submit" class="btn btn-primary">
                                отмена
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

appmailsend/templates/appmailsend/client_detail.html
{% extends 'appmailsend/base.html' %}
{% block content %}
<div class="col-6">
    <div class="cart">
        <div class="cart-body">

            <p class="card-text"> Имя - {{object.name}} </p>
            <p class="card-text"> Описание - {{object.description}} </p>
            <p class="card-text"> Почта - {{object.email }} </p>
            <p class="card-text"> Дата создания - {{object.date_of_creation }} </p>
            <p class="card-text"> Последнее изменение - {{object.last_modified_date }} </p>
            <p class="card-text"> Всего рассылок с клиентом - {{object.1 }} </p>
            <p class="card-text"> Отправлено писем клиенту - {{object.2 }} </p>


        </div>
    </div>
</div>
<!--<div class="col-6">-->
<!--    <div class="cart">-->
<!--        <div class="cart-header">-->
<!--            Version-->
<!--        </div>-->
<!--        <div class="cart-body">-->
<!--            {% for version in object.version_set.all %}-->
<!--                <li>{{ version }}</li>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
{% endblock %}

appmailsend/templates/appmailsend/client_form.html
{% extends 'appmailsend/base.html' %}

{% block content %}
<form method="post" class="row">

    <div class="col-6">
        <div class="cart">
            <div class="cart-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>

            </div>
        </div>
    </div>
<!--    <div class="col-6">-->
<!--        <div class="cart">-->
<!--            <div class="cart-header">-->
<!--                Version-->
<!--            </div>-->
<!--            <div class="cart-body">-->
<!--                {{ formset.management_form }}-->
<!--                {% for form in formset.forms %}-->
<!--                    {{ form.as_p }}-->
<!--                {% endfor %}-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

</form>
{% endblock %}

appmailsend/templates/appmailsend/client_list.html
{% extends 'appmailsend/base.html' %}

{% block content %}

<div class="row">
    <div class="col-12">
        <a href="{% url 'appmailsend:Client_create' %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Добавить клиента</a>
    </div>
{% for object in object_list%}
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">

            <div class="card-body">
                <p class="card-text">Пользователь {{object.owner}} </p>

                <p class="card-text"> {{object.name}} </p>
                <p class="card-text"> {{object.description}} </p>
                <p class="card-text"> дата создания {{object.date_of_creation}} </p>
                <p class="card-text"> последнее изменение {{object.last_modified_date}} </p>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'appmailsend:detail_Client' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Просмотр</a>
                        <a href="{% url 'appmailsend:Client_update' object.pk %}"  type="button"
                           class="btn btn-sm btn-outline-secondary">Изменить</a>
                        <a href="{% url 'appmailsend:Client_delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Удалить</a>

                    </div>
                    <small class="text-muted"></small>
                </div>
            </div>
        </div>
    </div>

{% endfor %}
</div>


{% endblock %}

appmailsend/templates/appmailsend/mailinglog_confirm_delete.html
{% extends 'appmailsend/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">

            <div class="col-10">
                <div class="cart">
                    <div class="cart-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить запись "{{ object }} "</p>
                            <button type="submit" class="btn btn-danger">
                                Продолжить
                            </button>
                            <a href="{% url 'appmailsend:MailingLog' %}"  type="submit" class="btn btn-primary">
                                отмена
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

appmailsend/templates/appmailsend/mailinglog_list.html
{% extends 'appmailsend/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">

    </div>
    {% for object in object_list%}
    <div class="card mb-4 shadow-sm">

            <div class="card-body">

                <p class="card-text"> Время рассылки {{object.time_mailing}} </p>
                <p class="card-text"> Успешная отправка {{object.succes_mail}} </p>
                <p class="card-text"> Ответ сервера {{object.answer}} </p>
                <p class="card-text"> Получатель {{object.client}} </p>
                <p class="card-text"> Создатель {{object.owner}} </p>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'appmailsend:mailinglog_detail' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Просмотр</a>

                    </div>
                    <small class="text-muted"></small>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}

appmailsend/templates/appmailsend/mailingsettings_confirm_delete.html
{% extends 'appmailsend/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">

            <div class="col-10">
                <div class="cart">
                    <div class="cart-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить запись "{{ object }} "</p>
                            <button type="submit" class="btn btn-danger">
                                Продолжить
                            </button>
                            <a href="{% url 'blog:list' %}"  type="submit" class="btn btn-primary">
                                отмена
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

appmailsend/templates/appmailsend/mailingsettings_list.html
{% extends 'appmailsend/base.html' %}

{% block content %}
<div class="row">
    <div class="col-12">
        <a href="{% url 'appmailsend:mailingsettings_create' %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Добавить настройку</a>
    </div>
    {% for object in object_list%}
    <div class="card mb-4 shadow-sm">

            <div class="card-body">

                <p class="card-text"> Время рассылки{{object.mailing_time}} </p>
                <p class="card-text"> Дата начала рассылки {{object.start_of_mailing}} </p>
                <p class="card-text"> График рассылки {{object.Mailing_schedule}} </p>
                <p class="card-text"> Статус {{object.status}} </p>

                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'appmailsend:mailingsettings_detail' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Просмотр</a>
                        <a href="{% url 'appmailsend:mailingsettings_update' object.pk %}"  type="button"
                           class="btn btn-sm btn-outline-secondary">Изменить</a>
                        <a href="{% url 'appmailsend:mailingsettings_delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Удалить</a>
                    </div>
                    <small class="text-muted"></small>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


{% endblock %}