blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListVeiw, BlogDetailVeiw, BlogUpdateView, BlogDeleteVeiw

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListVeiw.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailVeiw.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteVeiw.as_view(), name='delete'),
]
  # + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appmailsend.urls', namespace='appmailsend')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls',namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=150,verbose_name='Заголовок')
    description = models.TextField(verbose_name='Содержание')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата публикации', null=True, blank=True)
    image = models.ImageField(upload_to='image_Blog', verbose_name='изображение', null=True, blank=True)

    Published = models.BooleanField(default=True, verbose_name='Опубликовано')
    number_of_views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    slug = models.CharField(max_length=50, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('title',)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title','description','image')
    extra_context = {
        'title': 'Новая запись в блоге'
    }
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title','description','image')
    extra_context = {
        'title': 'Update блог'
    }
    # success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

class BlogListVeiw(ListView):
    model = Blog
    extra_context = {
        'title': 'Опубликованные записи в блоге'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(Published=True)
        return queryset
class BlogDetailVeiw(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)

        category_item = Blog.objects.get(pk=self.kwargs.get('pk'))
        context_data['title'] = f'Blog {category_item.title }'

        return context_data

class BlogDeleteVeiw(DeleteView):
    model = Blog
    extra_context = {
        'title': 'Delete блог'
    }
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'appmailsend/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">

            <div class="col-10">
                <div class="cart">
                    <div class="cart-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить запись "{{ object.title }}"</p>
                            <button type="submit" class="btn btn-danger">
                                Продолжить
                            </button>
                            <a href="{% url 'blog:list' %}"  type="submit" class="btn btn-primary">
                                отмена
                            </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'appmailsend/base.html' %}

{% block content %}
<div class="col-md-12">
    <div class="card mb-10 shadow-sm">
        <img src="/media/{{ object.image }}" class="img-fluid">

        <div class="card-body">
            <p class="card-text"> {{object.title}} ,slug ={{object.slug}} </p>
            <p class="card-text"> {{object.description}} </p>
            <small class="text-muted">Просмотры: {{object.number_of_views}}</small>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'appmailsend/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">

            <div class="col-10">
                <div class="cart">
                    <div class="cart-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'appmailsend/base.html' %}

{% block content %}
<div>
    <div class="btn-group">
        <a class="btn btn-primary" href="{% url 'blog:create' %}">Добавить запись</a>
    </div>
    <div class="row">

        {% for object in object_list%}
        {% include 'blog/includes/inc_blog.html' %}
        {% endfor %}
    </div>

</div>


{% endblock %}